### ISSUE TITLE
Error when creating new page with alternate parent/template user setup

### ISSUE THREAD

**Issue by adrianbj** [Toutouwai/BreadcrumbDropdowns#7]
HI @Toutouwai,

If you're making use of https://processwire.com/blog/posts/processwire-core-updates-2.5.14/#multiple-templates-or-parents-for-users the breadcrumb trail looks like: 
![image](https://user-images.githubusercontent.com/871211/75454000-98c80d00-5929-11ea-94e8-4ed6b45d3772.png)

rather than showing:
![image](https://user-images.githubusercontent.com/871211/75454055-abdadd00-5929-11ea-9f0e-3227e227bff4.png)

This is a bit annoying on its own but it matches what the PW core does with the breadcrumb in this situation (maybe I should file an issue for Ryan about this).

I guess the key issue is that clicking "Add New" results in "ProcessPageAdd: The template 'user' does not allow parents of type 'clients'" - do you think this can be fixed?

**Comment by Toutouwai** [comment]
Hi @adrianbj,

Although I've never used the multiple user parents/templates feature I'm inclined to think this should be fixed in ProcessUser rather than here (or perhaps in ProcessPageType seeing as ProcessUser extends that class). If multiple user parents/templates are configured I don't think ProcessUser should be forcing the `user` template during the add process but should rather select the correct template according to the `parent_id` GET variable, or let the user choose if multiple templates are allowed under the parent.

But I've pushed a fix anyway in v0.1.22 of BreadcrumbDropdowns. Let me know if this doesn't resolve it for you.

**Comment by adrianbj** [comment]
Thanks @Toutouwai - that seems to be working great. I think you're right that it should probably be fixed elsewhere though. Honestly, even though I find the multiple user parent/templates feature quite useful, I don't think it completely bug / idiosyncrasy free.

One thought for your module that is probably not really important, but perhaps `29` should be replaced with `$config->usersPageID` https://github.com/processwire/processwire/blob/51629cdd5f381d3881133baf83e1bd2d9306f867/wire/config.php#L1640

Thanks again!

**Comment by Toutouwai** [comment]
> perhaps 29 should be replaced with $config->usersPageID

Thanks, I've changed to that in the latest commit (no module version change).
